[programs.localnet]
gif_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nathanthomas/.config/solana/id.json"

[scripts]
test = "node tests/gif-program.js" 
